org: vyctorguimaraes
app: hello-sls-framework
service: hello-sls-framework
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main:
    handler: main.main
    events:
      - httpApi:
          path: /
          method: get
